<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2545" started-at="2018-11-06T08:43:23Z" finished-at="2018-11-06T08:43:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2545" started-at="2018-11-06T08:43:23Z" finished-at="2018-11-06T08:43:25Z">
      <class name="com.qa.tests.PostAPI_CreateNewCustomer">
        <test-method status="PASS" signature="custom_startTest()[pri:0, instance:com.qa.tests.PostAPI_CreateNewCustomer@604ed9f0]" name="custom_startTest" is-config="true" duration-ms="109" started-at="2018-11-06T14:13:23Z" finished-at="2018-11-06T14:13:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- custom_startTest -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.qa.tests.PostAPI_CreateNewCustomer@604ed9f0]" name="setup" is-config="true" duration-ms="0" started-at="2018-11-06T14:13:23Z" finished-at="2018-11-06T14:13:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="test_Post_API_Create()[pri:0, instance:com.qa.tests.PostAPI_CreateNewCustomer@604ed9f0]" name="test_Post_API_Create" duration-ms="1735" started-at="2018-11-06T14:13:23Z" finished-at="2018-11-06T14:13:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Post_API_Create -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.qa.tests.PostAPI_CreateNewCustomer@604ed9f0]" name="setup" is-config="true" duration-ms="1" started-at="2018-11-06T14:13:25Z" finished-at="2018-11-06T14:13:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="custom_getResult()[pri:0, instance:com.qa.tests.PostAPI_CreateNewCustomer@604ed9f0]" name="custom_getResult" is-config="true" duration-ms="0" started-at="2018-11-06T14:13:25Z" finished-at="2018-11-06T14:13:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- custom_getResult -->
        <test-method status="FAIL" signature="test_Post_API_Search()[pri:0, instance:com.qa.tests.PostAPI_CreateNewCustomer@604ed9f0]" name="test_Post_API_Search" duration-ms="653" started-at="2018-11-06T14:13:25Z" finished-at="2018-11-06T14:13:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [201] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [201] but found [200]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.qa.tests.PostAPI_CreateNewCustomer.test_Post_API_Search(PostAPI_CreateNewCustomer.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Post_API_Search -->
        <test-method status="PASS" signature="custom_getResult()[pri:0, instance:com.qa.tests.PostAPI_CreateNewCustomer@604ed9f0]" name="custom_getResult" is-config="true" duration-ms="0" started-at="2018-11-06T14:13:25Z" finished-at="2018-11-06T14:13:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- custom_getResult -->
        <test-method status="PASS" signature="custom_endTest()[pri:0, instance:com.qa.tests.PostAPI_CreateNewCustomer@604ed9f0]" name="custom_endTest" is-config="true" duration-ms="31" started-at="2018-11-06T14:13:25Z" finished-at="2018-11-06T14:13:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- custom_endTest -->
      </class> <!-- com.qa.tests.PostAPI_CreateNewCustomer -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
